# Nombre del flujo de trabajo: Deploy Node.js API
name: Deploy Node.js API

# Disparador: Este flujo se ejecutará automáticamente cada vez que se haga un push a la rama 'main'
on:
  push:
    branches:
      - main  # Especificamos que este flujo se activa solo cuando hay un push en la rama 'main'

# Definición de los trabajos (jobs) a ejecutar en este flujo
jobs:
  deploy:
    # El flujo se ejecutará en el último entorno de Ubuntu disponible (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Realizar el checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar la conexión SSH y ejecutar comandos en el servidor
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 147.93.47.10
          username: root
          password: Acuamic.2025
          port: 22
          script: |
            sudo chown -R $USER:$USER /var/www/PlanillaVladimir
            sudo chmod -R 755 /var/www/PlanillaVladimir
            cd /var/www/PlanillaVladimir
            git config --global user.email "carlosroart13@gmail.com"
            git config --global user.name "Robertoart13"
            sudo git stash
            git pull https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/Robertoart13/PlanillaVladimir.git main
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18 
            nvm use 18
            npm i --legacy-peer-deps
            /root/.nvm/versions/node/v22.15.1/bin/pm2 restart 0
           
